### ISSUE TITLE
How would you add more "aside" sections

### ISSUE THREAD

**Issue by alfC** [mlda065/friggeri-letter#4]
In the old version it was possible just by doing

```
\begin{aside}
  \section{about}
    aaa
    bbb
  \section{about}
    aaa
    bbb
\end{aside}
```

Now, this does not compile.

Is it still possible to add more than one section in the aside column?

**Comment by alfC** [comment]
For the moment I have this workaround: https://tex.stackexchange.com/a/384869/1871
but there must be a better way.

**Comment by mlda065** [comment]
I just changed how `aside` works in [this commit](https://github.com/mlda065/friggeri-letter/commit/3ccbc086f3c637e63f71bcdefd4c9a2409510328). Now you can do this with `\subsubsection`.

**Comment by vrono** [comment]
Thx for this great updated version of the friggeri template!

I saw on the to do list, that you plan to have the option to have the \aside only on the front page (as in the original template). Do you know a work around to achieve this now already?

**Comment by mlda065** [comment]
I don't have a workaround for that yet.

You're welcome to try, and submit a pull request when you figure it out.

To start with, open `friggeri-cv.cls. Look for `\newcommand\aside`.

move the contents of `\AddEveryPageHook` outside of `\AddEveryPageHook` (then delete `\AddEveryPageHook`).

That stops the aside appearing on pages other than the first.

But then you have to figure out how to change the text width for the pages which now have no aside. (Since there is now a huge left margin.)
I'm not sure how to do that. Possibly use `\AddEveryPageHook` (or similar) to redefine the margins for the main text.

Unfortunately I don't have time for this at the moment.
